### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by Electromaster232** [sensson/python-directadmin#1]
Hi,

I'm not sure if you still check this repository or will see this, but I'm wondering if you could add a license to this. The reason is that technically, the code cannot be used in a derivative work, meaning that nobody can legally use your API in their projects. From the GitHub license documentation:
```You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work```

I would recommend choosing an open license for this, such as the MIT license, or at least something that allows inclusion in proprietary works, such as the LGPL.

Thanks for your consideration.

**Comment by ju5t** [comment]
@Electromaster232, good point. I've added a license.
